Add /timecard feature to develop branch
BanklessDAO/discord-bots pull request #213
Opened 2021-10-27 22:32 UTC by jonvaljonathan

Add the /timecard feature's core functionality.

/timecard checkin
/timecard checkout
/timecard hours

2021-11-01 17:16 UTC, amaredeus commented
@jonvaljonathan Looks like your forked repo's develop branch is behind the org's develop branch. Can you try syncing it? https://github.com/jonvaljonathan/discord-bots/tree/develop there might be a button to do this easily on the github page for your repo

2021-11-02 15:12 UTC, amaredeus requested changes
PR is starting to shape up very well! Can we also jot down the change under CHANGELOG.md? Once that's down and the other comments are addressed, I think this PR will be ready for this week's release!

2021-11-02 15:12 UTC, amaredeus commented on src/app/schema/timecard/timecard.json
> +          "bsonType": ["number", null],
null should be enclosed in double quotations

2021-11-02 15:12 UTC, amaredeus commented on src/app/types/timecard.ts/Timecard.ts
> +}
yeah the linter doesn't seem to capture typescript types or interfaces 🤷

2021-11-03 14:25 UTC, amaredeus commented
Hmm it looks like the test cases are failing https://github.com/jonvaljonathan/discord-bots/runs/4092653720?check_suite_focus=true

If you run `yarn test` what do you see?

2021-11-03 15:33 UTC, amaredeus submitted a review, later dismissed

2021-11-04 01:33 UTC, nonsensecodes approved these changes

2021-11-04 02:24 UTC, merged